name: default.yaml
background_color: "#21283b"
todo_border_style: light
status_line_color: "#141018"
selected_task_background_color: "#373e4f"
selected_workspace_background_color: "#373e4f"
workspace_color: "#93a4c3"
selected_workspace_color: "#93a4c3"
pending_task_color: "#ebcb8b"
pending_task_background: "#373e4f"
completed_task_color: "#98c379"
completed_task_background: "#373e4f"
overdue_task_color: "#bf4a58"
overdue_task_background: "#373e4f"
urgency_low_color: "#54e7ac"
urgency_medium_color: "#d3e847"
urgency_high_color: "#e75462"
workspace_pointer: 
task_pointer: 
non_empty_workspace_icon: 
empty_workspace_icon: 
pending_task_icon: 
completed_task_icon: 
overdue_task_icon: 󰅗
urgency_low_icon: 󰿷
urgency_medium_icon: 
urgency_high_icon: 󰚌
due_time_icon: 
search_icon: 